### ISSUE TITLE
service COMENTS

### ISSUE THREAD

**Issue by JSeguiN97** [UB-ES-2018/instagram#41]
Implementar repositorio, modelo y servicio de la tabla

**Comment by abeljdrs** [comment]
la Issue-41 no esta lista para ser integrada a develop... falta el controlador del servicio con sus URL y el modelo de datos esta mal relacionado con las tablas.

**Comment by abeljdrs** [comment]
la Issue-41 no esta lista para ser integrada a develop... falta el controlador del servicio con sus URL y el modelo de datos esta mal relacionado con las tablas

**Comment by abeljdrs** [comment]
merged
